kind: Service
apiVersion: v1
metadata:
  name: myhelidonprojforoci
  labels:
    app: myhelidonprojforoci
spec:
  type: NodePort
  selector:
    app: myhelidonprojforoci
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myhelidonprojforoci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhelidonprojforoci
  template:
    metadata:
      labels:
        app: myhelidonprojforoci
        version: v1
    spec:
      containers:
      - name: myhelidonprojforoci
        image: myhelidonprojforoci
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
